name: emulate
description: Emulate unsupported operating systems using QEMU.
inputs:
  operating-system:
    description: The operating-system specifier.
    required: true
runs:
  using: composite
  steps:
  - name: Setup QEMU and the guest OS virtual machine.
    shell: bash
    env:
      GUEST_OS: ${{ inputs.operating-system }}
    run: |
      EMULATE_VAGRANT_PATH="$GITHUB_ACTION_PATH/$GUEST_OS"

      test -d "$EMULATE_VAGRANT_PATH"

      sudo apt-get install --yes --no-install-recommends \
        vagrant \
        vagrant-libvirt \
        libvirt-daemon \
        libvirt-daemon-system \
        qemu-kvm \
        qemu-utils \
        >/dev/null 2>&1

      # Intercept the `run` steps to send the script to the VM.
      BASH_ENV="$(mktemp)"
      echo "BASH_ENV=$BASH_ENV" >> "$GITHUB_ENV"
      cat >"$BASH_ENV" <<EOF
      read -r -a BASH_ARGS <<< "\$(ps -p \$$ -o args=)"
      cd '$EMULATE_VAGRANT_PATH'
      exec sudo vagrant ssh -c "\$(cat "\${BASH_ARGS[@]: -1:1}")"
      EOF

      cd "$EMULATE_VAGRANT_PATH"
      sudo nice -n -20 vagrant up
