name: emulate
description: Emulate unsupported operating systems using QEMU.
inputs:
  operating-system:
    description: The operating-system specifier.
    required: true
runs:
  using: composite
  steps:
  - name: Setup QEMU and the guest OS virtual machine.
    shell: bash
    env:
      GUEST_OS: ${{ inputs.operating-system }}
    run: |
      sudo apt-get install --yes --no-install-recommends \
        vagrant \
        vagrant-libvirt \
        libvirt-daemon \
        libvirt-daemon-system \
        qemu-kvm \
        qemu-utils \
        >/dev/null 2>&1
        
      # Intercept the `run` steps to send the script to the VM.
      sudo ln --force "$GITHUB_ACTION_PATH/shell" /bin/bash

      # The `vagrant ssh` command (in `shell`) is "path-aware", so it must be
      # executed from within the directory of the Vagrantfile. Rather than 
      # hardcode this path in `shell` or require the user to supply it, let's
      # persist it in the environment.
      echo "EMULATE_VAGRANT_PATH=$GITHUB_ACTION_PATH/$GUEST_OS" >> "$GITHUB_ENV"
      
      cd "$GITHUB_ACTION_PATH/$GUEST_OS"
      nice -n -20 sudo vagrant up
